### ISSUE TITLE
create onion dyeing page

### ISSUE THREAD

**Issue by njr2128** [cu-mkp/sandbox#103]
Within the `docs/` directory, create a new page called `su22_fld_cunningham_annika_onion-skin-dyeing.md`

Populate this page with the notes and images sent by Annika in an email. Images likely need to first be uploaded to Flickr

**Comment by njr2128** [comment]
To be determined: where in the listings of the Sandbox should this be?

**Comment by catkins2019** [comment]
#103: page has been created, keeping issue open until Sandbox location determined

**Comment by njr2128** [comment]
New section titled "Making Colors" was made and page is now featured on index page of sandbox
