### ISSUE TITLE
Present Roni's work in sandbox

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/sandbox#2]
see: https://github.com/ronikaufman/manuscript-object

**Comment by njr2128** [comment]
See - cu-mkp/manuscript-object#82 - created tagged releases of both Dana and Roni's code: https://github.com/cu-mkp/manuscript-object/tree/v1.0-danachaillard and https://github.com/cu-mkp/manuscript-object/releases/tag/v1.0-ronikaufman

**Comment by njr2128** [comment]
Create markdown of pdf - perhaps using tika (https://tika.apache.org/)

**Comment by njr2128** [comment]
Used online converter: https://pdf2md.morethan.io/ (see also their github: https://github.com/jzillmann/pdf-to-markdown)
