### ISSUE TITLE
present Dana's report and code in sandbox

### ISSUE THREAD

**Issue by tcatapano** [cu-mkp/sandbox#3]
see: 

https://github.com/danachaillard/manuscript-object/blob/master/Dana'sdoc.pdf

https://github.com/danachaillard/manuscript-object/

**Comment by njr2128** [comment]
see - cu-mkp/manuscript-object#82 - created tagged releases of both Dana and Roni's code: https://github.com/cu-mkp/manuscript-object/tree/v1.0-danachaillard and https://github.com/cu-mkp/manuscript-object/releases/tag/v1.0-ronikaufman

**Comment by njr2128** [comment]
Create markdown of pdf - perhaps using tika (https://tika.apache.org/)

**Comment by njr2128** [comment]
Used online converter: https://pdf2md.morethan.io/ (see also their github: https://github.com/jzillmann/pdf-to-markdown)
